DEFAULT_DATA_DIR = "apps/tradeSimulator"

DEFAULT_DATETIME_FORMAT = "%Y-%m-%dT%H:%M:%S"
CONNECTED_DATETIME_FORMAT = "%Y%m%d%H%M%S"

EVETYPE_TICK = 1
EVETYPE_ORDER = 2
EVETYPE_SIGNAL = 3

CMD_CREATE_MARKET_ORDER = 1
CMD_CREATE_LIMIT_ORDER = 2
CMD_CREATE_STOP_ORDER = 3
CMD_CANCEL = 4
CMD_CHANGE_TRADE = 5
CMD_ORDER_ERROR = -1

ORDERTYPE_ORDER = 1
ORDERTYPE_TRADE = 2

ESTATUS_NONE = 0
ESTATUS_ORDER_OPENED = 1
ESTATUS_ORDER_CLOSED = 2
ESTATUS_TRADE_OPENED = 3
ESTATUS_TRADE_CLOSED = 4
ESTATUS_ERROR = -1


TRADING_HISTORY_FLUSH_INTERVAL = 60*60 #move history events to db every hours

SIDE_BUY = 1
SIDE_SELL = -1

TICKTYPE_ONLINE = 1
TICKTYPE_OFFLINE = 2

ERROR_NONE = 0
ERROR_BAD_ORDER = 10

GENERAL_BATCH_SIZE = 10000

TICKER_ERR_NONE = 0
TICKER_NODATA = 1
TICKER_ERR_EOF = 2

TRADE_MODE_BOTH = 1
TRADE_MODE_ONLY_BUY = 2
TRADE_MODE_ONLY_SELL = 3

ZZ_MODE_RETURN_COMPLETED = 1
ZZ_MODE_RETURN_MIDDLE = 2
ZZ_MODE_RETURN_ONLY_LAST_MIDDLE = 3
ZZ_N_MIN_VOLUMES = 10
ZZ_MIN_VOLUMES = 10000
