CREATE TABLE IF NOT EXISTS zz_strtg_params (
    order_id VARCHAR(100),
    codename VARCHAR(50),
    side SMALLINT, 
    takeprofit_price FLOAT, 
    stoploss_price FLOAT,
    EP INT NOT NULL,
    DT TIMESTAMP,
    price FLOAT,
    trend INT,
    vol_rank INT,
    trade_pos_key INT,
    tp_diff FLOAT,
    prefer_recent_peaks INT,
    peak_broken SMALLINT,
    mado FLOAT,
    acc FLOAT,
    trend_rate FLOAT,
    chiko FLOAT,
    len_std FLOAT,
    hara_rate FLOAT,
    up_hige_rate FLOAT,
    dw_hige_rate FLOAT,
    len_avg FLOAT,
    reversed_cnt INT,
    momiai FLOAT,
    PRIMARY KEY (order_id)
);